### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by OhTaeHo-97** [OhTaeHo-97/Todo#1]
### 만들고자 하는 기능이 무엇인가요?
회원가입

### 해당 기능을 구현하기 위해 할 일이 무엇인가요?
1.  [ ] 회원 정보 관련 엔티티 생성
2.  [ ] 요청으로 전달받은 정보를 객체로 변경해줄 DTO 생성
3.  [ ] 회원가입을 위한 핸들러 메서드 생성
4.  [ ] DTO <-> 엔티티 간의 Mapper 생성
5.  [ ] DB에 회원 정보를 저장하기 위한 Repository 생성
6.  [ ] DB에 회원 정보를 저장하는 비즈니스 로직 생성 (유효성 검사 포함)

### 예상 작업 시간
1h 30m
